enable: false

aiType: deepseek

ai:
  deepseek:
    token:
    model: deepseek-chat

  openrouter:
    token:
    model:


threadpool:
  core: 16
  max: 64
  queue: 128
  keepalive: 60

conversation:
  keep: false
