enable: false

aiType: deepseek

ai:
  custom:
    url: http://localhost:11434/v1/chat/completions
    token:
    model: gpt-3.5-turbo

  deepseek:
    token:
    model: deepseek-chat

  openrouter:
    token:
    model:


threadpool:
  core: 16
  max: 64
  queue: 128
  keepalive: 60

conversation:
  keep: false
