name: MCEngineArtificialIntelligence
version: ${version}
main: io.github.mcengine.spigotmc.artificialintelligence.engine.MCEngineArtificialIntelligenceSpigotMC
author: MCEngine
description: MCEngine Artificial Intelligence
api-version: 1.18
commands:
  ai:
    description: Get AI response
    usage: /<command>
