package io.github.mcengine.api.artificialintelligence.functions.calling;

import org.bukkit.Material;
import java.util.Map;

public class FunctionCallingLoaderMCItem {

    public static final Map<String, Material> MATERIAL_ALIASES = Map.ofEntries(
        Map.entry("acacia boat", Material.ACACIA_BOAT),
        Map.entry("acacia button", Material.ACACIA_BUTTON),
        Map.entry("acacia chest boat", Material.ACACIA_CHEST_BOAT),
        Map.entry("acacia door", Material.ACACIA_DOOR),
        Map.entry("acacia fence", Material.ACACIA_FENCE),
        Map.entry("acacia fence gate", Material.ACACIA_FENCE_GATE),
        Map.entry("acacia hanging sign", Material.ACACIA_HANGING_SIGN),
        Map.entry("acacia leaves", Material.ACACIA_LEAVES),
        Map.entry("acacia log", Material.ACACIA_LOG),
        Map.entry("acacia planks", Material.ACACIA_PLANKS),
        Map.entry("acacia pressure plate", Material.ACACIA_PRESSURE_PLATE),
        Map.entry("acacia sapling", Material.ACACIA_SAPLING),
        Map.entry("acacia sign", Material.ACACIA_SIGN),
        Map.entry("acacia slab", Material.ACACIA_SLAB),
        Map.entry("acacia stairs", Material.ACACIA_STAIRS),
        Map.entry("acacia trapdoor", Material.ACACIA_TRAPDOOR),
        Map.entry("acacia wall hanging sign", Material.ACACIA_WALL_HANGING_SIGN),
        Map.entry("acacia wall sign", Material.ACACIA_WALL_SIGN),
        Map.entry("acacia wood", Material.ACACIA_WOOD),
        Map.entry("activator rail", Material.ACTIVATOR_RAIL),
        Map.entry("air", Material.AIR),
        Map.entry("allay spawn egg", Material.ALLAY_SPAWN_EGG),
        Map.entry("allium", Material.ALLIUM),
        Map.entry("amethyst block", Material.AMETHYST_BLOCK),
        Map.entry("amethyst cluster", Material.AMETHYST_CLUSTER),
        Map.entry("amethyst shard", Material.AMETHYST_SHARD),
        Map.entry("ancient debris", Material.ANCIENT_DEBRIS),
        Map.entry("andesite", Material.ANDESITE),
        Map.entry("andesite slab", Material.ANDESITE_SLAB),
        Map.entry("andesite stairs", Material.ANDESITE_STAIRS),
        Map.entry("andesite wall", Material.ANDESITE_WALL),
        Map.entry("angler pottery sherd", Material.ANGLER_POTTERY_SHERD),
        Map.entry("anvil", Material.ANVIL),
        Map.entry("apple", Material.APPLE),
        Map.entry("archer pottery sherd", Material.ARCHER_POTTERY_SHERD),
        Map.entry("armadillo scute", Material.ARMADILLO_SCUTE),
        Map.entry("armadillo spawn egg", Material.ARMADILLO_SPAWN_EGG),
        Map.entry("armor stand", Material.ARMOR_STAND),
        Map.entry("arms up pottery sherd", Material.ARMS_UP_POTTERY_SHERD),
        Map.entry("arrow", Material.ARROW),
        Map.entry("attached melon stem", Material.ATTACHED_MELON_STEM),
        Map.entry("attached pumpkin stem", Material.ATTACHED_PUMPKIN_STEM),
        Map.entry("axolotl bucket", Material.AXOLOTL_BUCKET),
        Map.entry("axolotl spawn egg", Material.AXOLOTL_SPAWN_EGG),
        Map.entry("azalea", Material.AZALEA),
        Map.entry("azalea leaves", Material.AZALEA_LEAVES),
        Map.entry("azure bluet", Material.AZURE_BLUET),
        Map.entry("baked potato", Material.BAKED_POTATO),
        Map.entry("bamboo", Material.BAMBOO),
        Map.entry("bamboo block", Material.BAMBOO_BLOCK),
        Map.entry("bamboo button", Material.BAMBOO_BUTTON),
        Map.entry("bamboo chest raft", Material.BAMBOO_CHEST_RAFT),
        Map.entry("bamboo door", Material.BAMBOO_DOOR),
        Map.entry("bamboo fence", Material.BAMBOO_FENCE),
        Map.entry("bamboo fence gate", Material.BAMBOO_FENCE_GATE),
        Map.entry("bamboo hanging sign", Material.BAMBOO_HANGING_SIGN),
        Map.entry("bamboo mosaic", Material.BAMBOO_MOSAIC),
        Map.entry("bamboo mosaic slab", Material.BAMBOO_MOSAIC_SLAB),
        Map.entry("bamboo mosaic stairs", Material.BAMBOO_MOSAIC_STAIRS),
        Map.entry("bamboo planks", Material.BAMBOO_PLANKS),
        Map.entry("bamboo pressure plate", Material.BAMBOO_PRESSURE_PLATE),
        Map.entry("bamboo raft", Material.BAMBOO_RAFT),
        Map.entry("bamboo sapling", Material.BAMBOO_SAPLING),
        Map.entry("bamboo sign", Material.BAMBOO_SIGN),
        Map.entry("bamboo slab", Material.BAMBOO_SLAB),
        Map.entry("bamboo stairs", Material.BAMBOO_STAIRS),
        Map.entry("bamboo trapdoor", Material.BAMBOO_TRAPDOOR),
        Map.entry("bamboo wall hanging sign", Material.BAMBOO_WALL_HANGING_SIGN),
        Map.entry("bamboo wall sign", Material.BAMBOO_WALL_SIGN),
        Map.entry("barrel", Material.BARREL),
        Map.entry("barrier", Material.BARRIER),
        Map.entry("basalt", Material.BASALT),
        Map.entry("bat spawn egg", Material.BAT_SPAWN_EGG),
        Map.entry("beacon", Material.BEACON),
        Map.entry("bedrock", Material.BEDROCK),
        Map.entry("bee nest", Material.BEE_NEST),
        Map.entry("bee spawn egg", Material.BEE_SPAWN_EGG),
        Map.entry("beef", Material.BEEF),
        Map.entry("beehive", Material.BEEHIVE),
        Map.entry("beetroot", Material.BEETROOT),
        Map.entry("beetroot seeds", Material.BEETROOT_SEEDS),
        Map.entry("beetroot soup", Material.BEETROOT_SOUP),
        Map.entry("beetroots", Material.BEETROOTS),
        Map.entry("bell", Material.BELL),
        Map.entry("big dripleaf", Material.BIG_DRIPLEAF),
        Map.entry("big dripleaf stem", Material.BIG_DRIPLEAF_STEM),
        Map.entry("birch boat", Material.BIRCH_BOAT),
        Map.entry("birch button", Material.BIRCH_BUTTON),
        Map.entry("birch chest boat", Material.BIRCH_CHEST_BOAT),
        Map.entry("birch door", Material.BIRCH_DOOR),
        Map.entry("birch fence", Material.BIRCH_FENCE),
        Map.entry("birch fence gate", Material.BIRCH_FENCE_GATE),
        Map.entry("birch hanging sign", Material.BIRCH_HANGING_SIGN),
        Map.entry("birch leaves", Material.BIRCH_LEAVES),
        Map.entry("birch log", Material.BIRCH_LOG),
        Map.entry("birch planks", Material.BIRCH_PLANKS),
        Map.entry("birch pressure plate", Material.BIRCH_PRESSURE_PLATE),
        Map.entry("birch sapling", Material.BIRCH_SAPLING),
        Map.entry("birch sign", Material.BIRCH_SIGN),
        Map.entry("birch slab", Material.BIRCH_SLAB),
        Map.entry("birch stairs", Material.BIRCH_STAIRS),
        Map.entry("birch trapdoor", Material.BIRCH_TRAPDOOR),
        Map.entry("birch wall hanging sign", Material.BIRCH_WALL_HANGING_SIGN),
        Map.entry("birch wall sign", Material.BIRCH_WALL_SIGN),
        Map.entry("birch wood", Material.BIRCH_WOOD),
        Map.entry("black banner", Material.BLACK_BANNER),
        Map.entry("black bed", Material.BLACK_BED),
        Map.entry("black bundle", Material.BLACK_BUNDLE),
        Map.entry("black candle", Material.BLACK_CANDLE),
        Map.entry("black candle cake", Material.BLACK_CANDLE_CAKE),
        Map.entry("black carpet", Material.BLACK_CARPET),
        Map.entry("black concrete", Material.BLACK_CONCRETE),
        Map.entry("black concrete powder", Material.BLACK_CONCRETE_POWDER),
        Map.entry("black dye", Material.BLACK_DYE),
        Map.entry("black glazed terracotta", Material.BLACK_GLAZED_TERRACOTTA),
        Map.entry("black shulker box", Material.BLACK_SHULKER_BOX),
        Map.entry("black stained glass", Material.BLACK_STAINED_GLASS),
        Map.entry("black stained glass pane", Material.BLACK_STAINED_GLASS_PANE),
        Map.entry("black terracotta", Material.BLACK_TERRACOTTA),
        Map.entry("black wall banner", Material.BLACK_WALL_BANNER),
        Map.entry("black wool", Material.BLACK_WOOL),
        Map.entry("blackstone", Material.BLACKSTONE),
        Map.entry("blackstone slab", Material.BLACKSTONE_SLAB),
        Map.entry("blackstone stairs", Material.BLACKSTONE_STAIRS),
        Map.entry("blackstone wall", Material.BLACKSTONE_WALL),
        Map.entry("blade pottery sherd", Material.BLADE_POTTERY_SHERD),
        Map.entry("blast furnace", Material.BLAST_FURNACE),
        Map.entry("blaze powder", Material.BLAZE_POWDER),
        Map.entry("blaze rod", Material.BLAZE_ROD),
        Map.entry("blaze spawn egg", Material.BLAZE_SPAWN_EGG),
        Map.entry("blue banner", Material.BLUE_BANNER),
        Map.entry("blue bed", Material.BLUE_BED),
        Map.entry("blue bundle", Material.BLUE_BUNDLE),
        Map.entry("blue candle", Material.BLUE_CANDLE),
        Map.entry("blue candle cake", Material.BLUE_CANDLE_CAKE),
        Map.entry("blue carpet", Material.BLUE_CARPET),
        Map.entry("blue concrete", Material.BLUE_CONCRETE),
        Map.entry("blue concrete powder", Material.BLUE_CONCRETE_POWDER),
        Map.entry("blue dye", Material.BLUE_DYE),
        Map.entry("blue egg", Material.BLUE_EGG),
        Map.entry("blue glazed terracotta", Material.BLUE_GLAZED_TERRACOTTA),
        Map.entry("blue ice", Material.BLUE_ICE),
        Map.entry("blue orchid", Material.BLUE_ORCHID),
        Map.entry("blue shulker box", Material.BLUE_SHULKER_BOX),
        Map.entry("blue stained glass", Material.BLUE_STAINED_GLASS),
        Map.entry("blue stained glass pane", Material.BLUE_STAINED_GLASS_PANE),
        Map.entry("blue terracotta", Material.BLUE_TERRACOTTA),
        Map.entry("blue wall banner", Material.BLUE_WALL_BANNER),
        Map.entry("blue wool", Material.BLUE_WOOL),
        Map.entry("bogged spawn egg", Material.BOGGED_SPAWN_EGG),
        Map.entry("bolt armor trim smithing template", Material.BOLT_ARMOR_TRIM_SMITHING_TEMPLATE),
        Map.entry("bone", Material.BONE),
        Map.entry("bone block", Material.BONE_BLOCK),
        Map.entry("bone meal", Material.BONE_MEAL),
        Map.entry("book", Material.BOOK),
        Map.entry("bookshelf", Material.BOOKSHELF),
        Map.entry("bordure indented banner pattern", Material.BORDURE_INDENTED_BANNER_PATTERN),
        Map.entry("bow", Material.BOW),
        Map.entry("bowl", Material.BOWL),
        Map.entry("brain coral", Material.BRAIN_CORAL),
        Map.entry("brain coral block", Material.BRAIN_CORAL_BLOCK),
        Map.entry("brain coral fan", Material.BRAIN_CORAL_FAN),
        Map.entry("brain coral wall fan", Material.BRAIN_CORAL_WALL_FAN),
        Map.entry("bread", Material.BREAD),
        Map.entry("breeze rod", Material.BREEZE_ROD),
        Map.entry("breeze spawn egg", Material.BREEZE_SPAWN_EGG),
        Map.entry("brewer pottery sherd", Material.BREWER_POTTERY_SHERD),
        Map.entry("brewing stand", Material.BREWING_STAND),
        Map.entry("brick", Material.BRICK),
        Map.entry("brick slab", Material.BRICK_SLAB),
        Map.entry("brick stairs", Material.BRICK_STAIRS),
        Map.entry("brick wall", Material.BRICK_WALL),
        Map.entry("bricks", Material.BRICKS),
        Map.entry("brown banner", Material.BROWN_BANNER),
        Map.entry("brown bed", Material.BROWN_BED),
        Map.entry("brown bundle", Material.BROWN_BUNDLE),
        Map.entry("brown candle", Material.BROWN_CANDLE),
        Map.entry("brown candle cake", Material.BROWN_CANDLE_CAKE),
        Map.entry("brown carpet", Material.BROWN_CARPET),
        Map.entry("brown concrete", Material.BROWN_CONCRETE),
        Map.entry("brown concrete powder", Material.BROWN_CONCRETE_POWDER),
        Map.entry("brown dye", Material.BROWN_DYE),
        Map.entry("brown egg", Material.BROWN_EGG),
        Map.entry("brown glazed terracotta", Material.BROWN_GLAZED_TERRACOTTA),
        Map.entry("brown mushroom", Material.BROWN_MUSHROOM),
        Map.entry("brown mushroom block", Material.BROWN_MUSHROOM_BLOCK),
        Map.entry("brown shulker box", Material.BROWN_SHULKER_BOX),
        Map.entry("brown stained glass", Material.BROWN_STAINED_GLASS),
        Map.entry("brown stained glass pane", Material.BROWN_STAINED_GLASS_PANE),
        Map.entry("brown terracotta", Material.BROWN_TERRACOTTA),
        Map.entry("brown wall banner", Material.BROWN_WALL_BANNER),
        Map.entry("brown wool", Material.BROWN_WOOL),
        Map.entry("brush", Material.BRUSH),
        Map.entry("bubble column", Material.BUBBLE_COLUMN),
        Map.entry("bubble coral", Material.BUBBLE_CORAL),
        Map.entry("bubble coral block", Material.BUBBLE_CORAL_BLOCK),
        Map.entry("bubble coral fan", Material.BUBBLE_CORAL_FAN),
        Map.entry("bubble coral wall fan", Material.BUBBLE_CORAL_WALL_FAN),
        Map.entry("bucket", Material.BUCKET),
        Map.entry("budding amethyst", Material.BUDDING_AMETHYST),
        Map.entry("bundle", Material.BUNDLE),
        Map.entry("burn pottery sherd", Material.BURN_POTTERY_SHERD),
        Map.entry("bush", Material.BUSH)
    );

    public static String applyMaterialPlaceholders(String input) {
        for (Map.Entry<String, Material> entry : MATERIAL_ALIASES.entrySet()) {
            input = input.replace(entry.getKey(), entry.getValue().name());
        }
        return input;
    }
}
