package io.github.mcengine.api.artificialintelligence.functions.calling;

import org.bukkit.Material;
import java.util.Map;

public class FunctionCallingLoaderMCItem {

    // https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    public static final Map<String, Material> MATERIAL_ALIASES = Map.ofEntries(
        Map.entry("acacia boat", Material.ACACIA_BOAT),
        Map.entry("acacia button", Material.ACACIA_BUTTON),
        Map.entry("acacia chest boat", Material.ACACIA_CHEST_BOAT),
        Map.entry("acacia door", Material.ACACIA_DOOR),
        Map.entry("acacia fence", Material.ACACIA_FENCE),
        Map.entry("acacia fence gate", Material.ACACIA_FENCE_GATE),
        Map.entry("acacia hanging sign", Material.ACACIA_HANGING_SIGN),
        Map.entry("acacia leaves", Material.ACACIA_LEAVES),
        Map.entry("acacia log", Material.ACACIA_LOG),
        Map.entry("acacia planks", Material.ACACIA_PLANKS),
        Map.entry("acacia pressure plate", Material.ACACIA_PRESSURE_PLATE),
        Map.entry("acacia sapling", Material.ACACIA_SAPLING),
        Map.entry("acacia sign", Material.ACACIA_SIGN),
        Map.entry("acacia slab", Material.ACACIA_SLAB),
        Map.entry("acacia stairs", Material.ACACIA_STAIRS),
        Map.entry("acacia trapdoor", Material.ACACIA_TRAPDOOR),
        Map.entry("acacia wall hanging sign", Material.ACACIA_WALL_HANGING_SIGN),
        Map.entry("acacia wall sign", Material.ACACIA_WALL_SIGN),
        Map.entry("acacia wood", Material.ACACIA_WOOD),
        Map.entry("activator rail", Material.ACTIVATOR_RAIL),
        Map.entry("air", Material.AIR),
        Map.entry("allay spawn egg", Material.ALLAY_SPAWN_EGG),
        Map.entry("allium", Material.ALLIUM),
        Map.entry("amethyst block", Material.AMETHYST_BLOCK),
        Map.entry("amethyst cluster", Material.AMETHYST_CLUSTER),
        Map.entry("amethyst shard", Material.AMETHYST_SHARD),
        Map.entry("ancient debris", Material.ANCIENT_DEBRIS),
        Map.entry("andesite", Material.ANDESITE),
        Map.entry("andesite slab", Material.ANDESITE_SLAB),
        Map.entry("andesite stairs", Material.ANDESITE_STAIRS),
        Map.entry("andesite wall", Material.ANDESITE_WALL),
        Map.entry("angler pottery sherd", Material.ANGLER_POTTERY_SHERD),
        Map.entry("anvil", Material.ANVIL),
        Map.entry("apple", Material.APPLE),
        Map.entry("archer pottery sherd", Material.ARCHER_POTTERY_SHERD),
        Map.entry("armadillo scute", Material.ARMADILLO_SCUTE),
        Map.entry("armadillo spawn egg", Material.ARMADILLO_SPAWN_EGG),
        Map.entry("armor stand", Material.ARMOR_STAND),
        Map.entry("arms up pottery sherd", Material.ARMS_UP_POTTERY_SHERD),
        Map.entry("arrow", Material.ARROW),
        Map.entry("attached melon stem", Material.ATTACHED_MELON_STEM),
        Map.entry("attached pumpkin stem", Material.ATTACHED_PUMPKIN_STEM),
        Map.entry("axolotl bucket", Material.AXOLOTL_BUCKET),
        Map.entry("axolotl spawn egg", Material.AXOLOTL_SPAWN_EGG),
        Map.entry("azalea", Material.AZALEA),
        Map.entry("azalea leaves", Material.AZALEA_LEAVES),
        Map.entry("azure bluet", Material.AZURE_BLUET),
        Map.entry("baked potato", Material.BAKED_POTATO),
        Map.entry("bamboo", Material.BAMBOO),
        Map.entry("bamboo block", Material.BAMBOO_BLOCK),
        Map.entry("bamboo button", Material.BAMBOO_BUTTON),
        Map.entry("bamboo chest raft", Material.BAMBOO_CHEST_RAFT),
        Map.entry("bamboo door", Material.BAMBOO_DOOR),
        Map.entry("bamboo fence", Material.BAMBOO_FENCE),
        Map.entry("bamboo fence gate", Material.BAMBOO_FENCE_GATE),
        Map.entry("bamboo hanging sign", Material.BAMBOO_HANGING_SIGN),
        Map.entry("bamboo mosaic", Material.BAMBOO_MOSAIC),
        Map.entry("bamboo mosaic slab", Material.BAMBOO_MOSAIC_SLAB),
        Map.entry("bamboo mosaic stairs", Material.BAMBOO_MOSAIC_STAIRS),
        Map.entry("bamboo planks", Material.BAMBOO_PLANKS),
        Map.entry("bamboo pressure plate", Material.BAMBOO_PRESSURE_PLATE),
        Map.entry("bamboo raft", Material.BAMBOO_RAFT),
        Map.entry("bamboo sapling", Material.BAMBOO_SAPLING),
        Map.entry("bamboo sign", Material.BAMBOO_SIGN),
        Map.entry("bamboo slab", Material.BAMBOO_SLAB),
        Map.entry("bamboo stairs", Material.BAMBOO_STAIRS),
        Map.entry("bamboo trapdoor", Material.BAMBOO_TRAPDOOR),
        Map.entry("bamboo wall hanging sign", Material.BAMBOO_WALL_HANGING_SIGN),
        Map.entry("bamboo wall sign", Material.BAMBOO_WALL_SIGN),
        Map.entry("barrel", Material.BARREL),
        Map.entry("barrier", Material.BARRIER),
        Map.entry("basalt", Material.BASALT),
        Map.entry("bat spawn egg", Material.BAT_SPAWN_EGG),
        Map.entry("beacon", Material.BEACON),
        Map.entry("bedrock", Material.BEDROCK),
        Map.entry("bee nest", Material.BEE_NEST),
        Map.entry("bee spawn egg", Material.BEE_SPAWN_EGG),
        Map.entry("beef", Material.BEEF),
        Map.entry("beehive", Material.BEEHIVE),
        Map.entry("beetroot", Material.BEETROOT),
        Map.entry("beetroot seeds", Material.BEETROOT_SEEDS),
        Map.entry("beetroot soup", Material.BEETROOT_SOUP),
        Map.entry("beetroots", Material.BEETROOTS),
        Map.entry("bell", Material.BELL),
        Map.entry("big dripleaf", Material.BIG_DRIPLEAF),
        Map.entry("big dripleaf stem", Material.BIG_DRIPLEAF_STEM),
        Map.entry("birch boat", Material.BIRCH_BOAT),
        Map.entry("birch button", Material.BIRCH_BUTTON),
        Map.entry("birch chest boat", Material.BIRCH_CHEST_BOAT),
        Map.entry("birch door", Material.BIRCH_DOOR),
        Map.entry("birch fence", Material.BIRCH_FENCE),
        Map.entry("birch fence gate", Material.BIRCH_FENCE_GATE),
        Map.entry("birch hanging sign", Material.BIRCH_HANGING_SIGN),
        Map.entry("birch leaves", Material.BIRCH_LEAVES),
        Map.entry("birch log", Material.BIRCH_LOG),
        Map.entry("birch planks", Material.BIRCH_PLANKS),
        Map.entry("birch pressure plate", Material.BIRCH_PRESSURE_PLATE),
        Map.entry("birch sapling", Material.BIRCH_SAPLING),
        Map.entry("birch sign", Material.BIRCH_SIGN),
        Map.entry("birch slab", Material.BIRCH_SLAB),
        Map.entry("birch stairs", Material.BIRCH_STAIRS),
        Map.entry("birch trapdoor", Material.BIRCH_TRAPDOOR),
        Map.entry("birch wall hanging sign", Material.BIRCH_WALL_HANGING_SIGN),
        Map.entry("birch wall sign", Material.BIRCH_WALL_SIGN),
        Map.entry("birch wood", Material.BIRCH_WOOD),
        Map.entry("black banner", Material.BLACK_BANNER),
        Map.entry("black bed", Material.BLACK_BED),
        Map.entry("black bundle", Material.BLACK_BUNDLE),
        Map.entry("black candle", Material.BLACK_CANDLE),
        Map.entry("black candle cake", Material.BLACK_CANDLE_CAKE),
        Map.entry("black carpet", Material.BLACK_CARPET),
        Map.entry("black concrete", Material.BLACK_CONCRETE),
        Map.entry("black concrete powder", Material.BLACK_CONCRETE_POWDER),
        Map.entry("black dye", Material.BLACK_DYE),
        Map.entry("black glazed terracotta", Material.BLACK_GLAZED_TERRACOTTA),
        Map.entry("black shulker box", Material.BLACK_SHULKER_BOX),
        Map.entry("black stained glass", Material.BLACK_STAINED_GLASS),
        Map.entry("black stained glass pane", Material.BLACK_STAINED_GLASS_PANE),
        Map.entry("black terracotta", Material.BLACK_TERRACOTTA),
        Map.entry("black wall banner", Material.BLACK_WALL_BANNER),
        Map.entry("black wool", Material.BLACK_WOOL),
        Map.entry("blackstone", Material.BLACKSTONE),
        Map.entry("blackstone slab", Material.BLACKSTONE_SLAB),
        Map.entry("blackstone stairs", Material.BLACKSTONE_STAIRS),
        Map.entry("blackstone wall", Material.BLACKSTONE_WALL),
        Map.entry("blade pottery sherd", Material.BLADE_POTTERY_SHERD),
        Map.entry("blast furnace", Material.BLAST_FURNACE),
        Map.entry("blaze powder", Material.BLAZE_POWDER),
        Map.entry("blaze rod", Material.BLAZE_ROD),
        Map.entry("blaze spawn egg", Material.BLAZE_SPAWN_EGG),
        Map.entry("blue banner", Material.BLUE_BANNER),
        Map.entry("blue bed", Material.BLUE_BED),
        Map.entry("blue bundle", Material.BLUE_BUNDLE),
        Map.entry("blue candle", Material.BLUE_CANDLE),
        Map.entry("blue candle cake", Material.BLUE_CANDLE_CAKE),
        Map.entry("blue carpet", Material.BLUE_CARPET),
        Map.entry("blue concrete", Material.BLUE_CONCRETE),
        Map.entry("blue concrete powder", Material.BLUE_CONCRETE_POWDER),
        Map.entry("blue dye", Material.BLUE_DYE),
        Map.entry("blue egg", Material.BLUE_EGG),
        Map.entry("blue glazed terracotta", Material.BLUE_GLAZED_TERRACOTTA),
        Map.entry("blue ice", Material.BLUE_ICE),
        Map.entry("blue orchid", Material.BLUE_ORCHID),
        Map.entry("blue shulker box", Material.BLUE_SHULKER_BOX),
        Map.entry("blue stained glass", Material.BLUE_STAINED_GLASS),
        Map.entry("blue stained glass pane", Material.BLUE_STAINED_GLASS_PANE),
        Map.entry("blue terracotta", Material.BLUE_TERRACOTTA),
        Map.entry("blue wall banner", Material.BLUE_WALL_BANNER),
        Map.entry("blue wool", Material.BLUE_WOOL),
        Map.entry("bogged spawn egg", Material.BOGGED_SPAWN_EGG),
        Map.entry("bolt armor trim smithing template", Material.BOLT_ARMOR_TRIM_SMITHING_TEMPLATE),
        Map.entry("bone", Material.BONE),
        Map.entry("bone block", Material.BONE_BLOCK),
        Map.entry("bone meal", Material.BONE_MEAL),
        Map.entry("book", Material.BOOK),
        Map.entry("bookshelf", Material.BOOKSHELF),
        Map.entry("bordure indented banner pattern", Material.BORDURE_INDENTED_BANNER_PATTERN),
        Map.entry("bow", Material.BOW),
        Map.entry("bowl", Material.BOWL),
        Map.entry("brain coral", Material.BRAIN_CORAL),
        Map.entry("brain coral block", Material.BRAIN_CORAL_BLOCK),
        Map.entry("brain coral fan", Material.BRAIN_CORAL_FAN),
        Map.entry("brain coral wall fan", Material.BRAIN_CORAL_WALL_FAN),
        Map.entry("bread", Material.BREAD),
        Map.entry("breeze rod", Material.BREEZE_ROD),
        Map.entry("breeze spawn egg", Material.BREEZE_SPAWN_EGG),
        Map.entry("brewer pottery sherd", Material.BREWER_POTTERY_SHERD),
        Map.entry("brewing stand", Material.BREWING_STAND),
        Map.entry("brick", Material.BRICK),
        Map.entry("brick slab", Material.BRICK_SLAB),
        Map.entry("brick stairs", Material.BRICK_STAIRS),
        Map.entry("brick wall", Material.BRICK_WALL),
        Map.entry("bricks", Material.BRICKS),
        Map.entry("brown banner", Material.BROWN_BANNER),
        Map.entry("brown bed", Material.BROWN_BED),
        Map.entry("brown bundle", Material.BROWN_BUNDLE),
        Map.entry("brown candle", Material.BROWN_CANDLE),
        Map.entry("brown candle cake", Material.BROWN_CANDLE_CAKE),
        Map.entry("brown carpet", Material.BROWN_CARPET),
        Map.entry("brown concrete", Material.BROWN_CONCRETE),
        Map.entry("brown concrete powder", Material.BROWN_CONCRETE_POWDER),
        Map.entry("brown dye", Material.BROWN_DYE),
        Map.entry("brown egg", Material.BROWN_EGG),
        Map.entry("brown glazed terracotta", Material.BROWN_GLAZED_TERRACOTTA),
        Map.entry("brown mushroom", Material.BROWN_MUSHROOM),
        Map.entry("brown mushroom block", Material.BROWN_MUSHROOM_BLOCK),
        Map.entry("brown shulker box", Material.BROWN_SHULKER_BOX),
        Map.entry("brown stained glass", Material.BROWN_STAINED_GLASS),
        Map.entry("brown stained glass pane", Material.BROWN_STAINED_GLASS_PANE),
        Map.entry("brown terracotta", Material.BROWN_TERRACOTTA),
        Map.entry("brown wall banner", Material.BROWN_WALL_BANNER),
        Map.entry("brown wool", Material.BROWN_WOOL),
        Map.entry("brush", Material.BRUSH),
        Map.entry("bubble column", Material.BUBBLE_COLUMN),
        Map.entry("bubble coral", Material.BUBBLE_CORAL),
        Map.entry("bubble coral block", Material.BUBBLE_CORAL_BLOCK),
        Map.entry("bubble coral fan", Material.BUBBLE_CORAL_FAN),
        Map.entry("bubble coral wall fan", Material.BUBBLE_CORAL_WALL_FAN),
        Map.entry("bucket", Material.BUCKET),
        Map.entry("budding amethyst", Material.BUDDING_AMETHYST),
        Map.entry("bundle", Material.BUNDLE),
        Map.entry("burn pottery sherd", Material.BURN_POTTERY_SHERD),
        Map.entry("bush", Material.BUSH),
        Map.entry("cactus", Material.CACTUS),
        Map.entry("cactus flower", Material.CACTUS_FLOWER),
        Map.entry("cake", Material.CAKE),
        Map.entry("calcite", Material.CALCITE),
        Map.entry("calibrated sculk sensor", Material.CALIBRATED_SCULK_SENSOR),
        Map.entry("camel spawn egg", Material.CAMEL_SPAWN_EGG),
        Map.entry("campfire", Material.CAMPFIRE),
        Map.entry("candle", Material.CANDLE),
        Map.entry("candle cake", Material.CANDLE_CAKE),
        Map.entry("carrot", Material.CARROT),
        Map.entry("carrot on a stick", Material.CARROT_ON_A_STICK),
        Map.entry("carrots", Material.CARROTS),
        Map.entry("cartography table", Material.CARTOGRAPHY_TABLE),
        Map.entry("carved pumpkin", Material.CARVED_PUMPKIN),
        Map.entry("cat spawn egg", Material.CAT_SPAWN_EGG),
        Map.entry("cauldron", Material.CAULDRON),
        Map.entry("cave air", Material.CAVE_AIR),
        Map.entry("cave spider spawn egg", Material.CAVE_SPIDER_SPAWN_EGG),
        Map.entry("cave vines", Material.CAVE_VINES),
        Map.entry("cave vines plant", Material.CAVE_VINES_PLANT),
        Map.entry("chain", Material.CHAIN),
        Map.entry("chain command block", Material.CHAIN_COMMAND_BLOCK),
        Map.entry("chainmail boots", Material.CHAINMAIL_BOOTS),
        Map.entry("chainmail chestplate", Material.CHAINMAIL_CHESTPLATE),
        Map.entry("chainmail helmet", Material.CHAINMAIL_HELMET),
        Map.entry("chainmail leggings", Material.CHAINMAIL_LEGGINGS),
        Map.entry("charcoal", Material.CHARCOAL),
        Map.entry("cherry boat", Material.CHERRY_BOAT),
        Map.entry("cherry button", Material.CHERRY_BUTTON),
        Map.entry("cherry chest boat", Material.CHERRY_CHEST_BOAT),
        Map.entry("cherry door", Material.CHERRY_DOOR),
        Map.entry("cherry fence", Material.CHERRY_FENCE),
        Map.entry("cherry fence gate", Material.CHERRY_FENCE_GATE),
        Map.entry("cherry hanging sign", Material.CHERRY_HANGING_SIGN),
        Map.entry("cherry leaves", Material.CHERRY_LEAVES),
        Map.entry("cherry log", Material.CHERRY_LOG),
        Map.entry("cherry planks", Material.CHERRY_PLANKS),
        Map.entry("cherry pressure plate", Material.CHERRY_PRESSURE_PLATE),
        Map.entry("cherry sapling", Material.CHERRY_SAPLING),
        Map.entry("cherry sign", Material.CHERRY_SIGN),
        Map.entry("cherry slab", Material.CHERRY_SLAB),
        Map.entry("cherry stairs", Material.CHERRY_STAIRS),
        Map.entry("cherry trapdoor", Material.CHERRY_TRAPDOOR),
        Map.entry("cherry wall hanging sign", Material.CHERRY_WALL_HANGING_SIGN),
        Map.entry("cherry wall sign", Material.CHERRY_WALL_SIGN),
        Map.entry("cherry wood", Material.CHERRY_WOOD),
        Map.entry("chest", Material.CHEST),
        Map.entry("chest minecart", Material.CHEST_MINECART),
        Map.entry("chicken", Material.CHICKEN),
        Map.entry("chicken spawn egg", Material.CHICKEN_SPAWN_EGG),
        Map.entry("chipped anvil", Material.CHIPPED_ANVIL),
        Map.entry("chiseled bookshelf", Material.CHISELED_BOOKSHELF),
        Map.entry("chiseled copper", Material.CHISELED_COPPER),
        Map.entry("chiseled deepslate", Material.CHISELED_DEEPSLATE),
        Map.entry("chiseled nether bricks", Material.CHISELED_NETHER_BRICKS),
        Map.entry("chiseled polished blackstone", Material.CHISELED_POLISHED_BLACKSTONE),
        Map.entry("chiseled quartz block", Material.CHISELED_QUARTZ_BLOCK),
        Map.entry("chiseled red sandstone", Material.CHISELED_RED_SANDSTONE),
        Map.entry("chiseled resin bricks", Material.CHISELED_RESIN_BRICKS),
        Map.entry("chiseled sandstone", Material.CHISELED_SANDSTONE),
        Map.entry("chiseled stone bricks", Material.CHISELED_STONE_BRICKS),
        Map.entry("chiseled tuff", Material.CHISELED_TUFF),
        Map.entry("chiseled tuff bricks", Material.CHISELED_TUFF_BRICKS),
        Map.entry("chorus flower", Material.CHORUS_FLOWER),
        Map.entry("chorus fruit", Material.CHORUS_FRUIT),
        Map.entry("chorus plant", Material.CHORUS_PLANT),
        Map.entry("clay", Material.CLAY),
        Map.entry("clay ball", Material.CLAY_BALL),
        Map.entry("clock", Material.CLOCK),
        Map.entry("closed eyeblossom", Material.CLOSED_EYEBLOSSOM),
        Map.entry("coal", Material.COAL),
        Map.entry("coal block", Material.COAL_BLOCK),
        Map.entry("coal ore", Material.COAL_ORE),
        Map.entry("coarse dirt", Material.COARSE_DIRT),
        Map.entry("coast armor trim smithing template", Material.COAST_ARMOR_TRIM_SMITHING_TEMPLATE),
        Map.entry("cobbled deepslate", Material.COBBLED_DEEPSLATE),
        Map.entry("cobbled deepslate slab", Material.COBBLED_DEEPSLATE_SLAB),
        Map.entry("cobbled deepslate stairs", Material.COBBLED_DEEPSLATE_STAIRS),
        Map.entry("cobbled deepslate wall", Material.COBBLED_DEEPSLATE_WALL),
        Map.entry("cobblestone", Material.COBBLESTONE),
        Map.entry("cobblestone slab", Material.COBBLESTONE_SLAB),
        Map.entry("cobblestone stairs", Material.COBBLESTONE_STAIRS),
        Map.entry("cobblestone wall", Material.COBBLESTONE_WALL),
        Map.entry("cobweb", Material.COBWEB),
        Map.entry("cocoa", Material.COCOA),
        Map.entry("cocoa beans", Material.COCOA_BEANS),
        Map.entry("cod", Material.COD),
        Map.entry("cod bucket", Material.COD_BUCKET),
        Map.entry("cod spawn egg", Material.COD_SPAWN_EGG),
        Map.entry("command block", Material.COMMAND_BLOCK),
        Map.entry("command block minecart", Material.COMMAND_BLOCK_MINECART),
        Map.entry("comparator", Material.COMPARATOR),
        Map.entry("compass", Material.COMPASS),
        Map.entry("composter", Material.COMPOSTER),
        Map.entry("conduit", Material.CONDUIT),
        Map.entry("cooked beef", Material.COOKED_BEEF),
        Map.entry("cooked chicken", Material.COOKED_CHICKEN),
        Map.entry("cooked cod", Material.COOKED_COD),
        Map.entry("cooked mutton", Material.COOKED_MUTTON),
        Map.entry("cooked porkchop", Material.COOKED_PORKCHOP),
        Map.entry("cooked rabbit", Material.COOKED_RABBIT),
        Map.entry("cooked salmon", Material.COOKED_SALMON),
        Map.entry("cookie", Material.COOKIE),
        Map.entry("copper block", Material.COPPER_BLOCK),
        Map.entry("copper bulb", Material.COPPER_BULB),
        Map.entry("copper door", Material.COPPER_DOOR),
        Map.entry("copper grate", Material.COPPER_GRATE),
        Map.entry("copper ingot", Material.COPPER_INGOT),
        Map.entry("copper ore", Material.COPPER_ORE),
        Map.entry("copper trapdoor", Material.COPPER_TRAPDOOR),
        Map.entry("cornflower", Material.CORNFLOWER),
        Map.entry("cow spawn egg", Material.COW_SPAWN_EGG),
        Map.entry("cracked deepslate bricks", Material.CRACKED_DEEPSLATE_BRICKS),
        Map.entry("cracked deepslate tiles", Material.CRACKED_DEEPSLATE_TILES),
        Map.entry("cracked nether bricks", Material.CRACKED_NETHER_BRICKS),
        Map.entry("cracked polished blackstone bricks", Material.CRACKED_POLISHED_BLACKSTONE_BRICKS),
        Map.entry("cracked stone bricks", Material.CRACKED_STONE_BRICKS),
        Map.entry("crafter", Material.CRAFTER),
        Map.entry("crafting table", Material.CRAFTING_TABLE),
        Map.entry("creaking heart", Material.CREAKING_HEART),
        Map.entry("creaking spawn egg", Material.CREAKING_SPAWN_EGG),
        Map.entry("creeper banner pattern", Material.CREEPER_BANNER_PATTERN),
        Map.entry("creeper head", Material.CREEPER_HEAD),
        Map.entry("creeper spawn egg", Material.CREEPER_SPAWN_EGG),
        Map.entry("creeper wall head", Material.CREEPER_WALL_HEAD),
        Map.entry("crimson button", Material.CRIMSON_BUTTON),
        Map.entry("crimson door", Material.CRIMSON_DOOR),
        Map.entry("crimson fence", Material.CRIMSON_FENCE),
        Map.entry("crimson fence gate", Material.CRIMSON_FENCE_GATE),
        Map.entry("crimson fungus", Material.CRIMSON_FUNGUS),
        Map.entry("crimson hanging sign", Material.CRIMSON_HANGING_SIGN),
        Map.entry("crimson hyphae", Material.CRIMSON_HYPHAE),
        Map.entry("crimson nylium", Material.CRIMSON_NYLIUM),
        Map.entry("crimson planks", Material.CRIMSON_PLANKS),
        Map.entry("crimson pressure plate", Material.CRIMSON_PRESSURE_PLATE),
        Map.entry("crimson roots", Material.CRIMSON_ROOTS),
        Map.entry("crimson sign", Material.CRIMSON_SIGN),
        Map.entry("crimson slab", Material.CRIMSON_SLAB),
        Map.entry("crimson stairs", Material.CRIMSON_STAIRS),
        Map.entry("crimson stem", Material.CRIMSON_STEM),
        Map.entry("crimson trapdoor", Material.CRIMSON_TRAPDOOR),
        Map.entry("crimson wall hanging sign", Material.CRIMSON_WALL_HANGING_SIGN),
        Map.entry("crimson wall sign", Material.CRIMSON_WALL_SIGN),
        Map.entry("crossbow", Material.CROSSBOW),
        Map.entry("crying obsidian", Material.CRYING_OBSIDIAN),
        Map.entry("cut copper", Material.CUT_COPPER),
        Map.entry("cut copper slab", Material.CUT_COPPER_SLAB),
        Map.entry("cut copper stairs", Material.CUT_COPPER_STAIRS),
        Map.entry("cut red sandstone", Material.CUT_RED_SANDSTONE),
        Map.entry("cut red sandstone slab", Material.CUT_RED_SANDSTONE_SLAB),
        Map.entry("cut sandstone", Material.CUT_SANDSTONE),
        Map.entry("cut sandstone slab", Material.CUT_SANDSTONE_SLAB),
        Map.entry("cyan banner", Material.CYAN_BANNER),
        Map.entry("cyan bed", Material.CYAN_BED),
        Map.entry("cyan bundle", Material.CYAN_BUNDLE),
        Map.entry("cyan candle", Material.CYAN_CANDLE),
        Map.entry("cyan candle cake", Material.CYAN_CANDLE_CAKE),
        Map.entry("cyan carpet", Material.CYAN_CARPET),
        Map.entry("cyan concrete", Material.CYAN_CONCRETE),
        Map.entry("cyan concrete powder", Material.CYAN_CONCRETE_POWDER),
        Map.entry("cyan dye", Material.CYAN_DYE),
        Map.entry("cyan glazed terracotta", Material.CYAN_GLAZED_TERRACOTTA),
        Map.entry("cyan shulker box", Material.CYAN_SHULKER_BOX),
        Map.entry("cyan stained glass", Material.CYAN_STAINED_GLASS),
        Map.entry("cyan stained glass pane", Material.CYAN_STAINED_GLASS_PANE),
        Map.entry("cyan terracotta", Material.CYAN_TERRACOTTA),
        Map.entry("cyan wall banner", Material.CYAN_WALL_BANNER),
        Map.entry("cyan wool", Material.CYAN_WOOL),
        Map.entry("damaged anvil", Material.DAMAGED_ANVIL),
        Map.entry("dandelion", Material.DANDELION),
        Map.entry("danger pottery sherd", Material.DANGER_POTTERY_SHERD),
        Map.entry("dark oak boat", Material.DARK_OAK_BOAT),
        Map.entry("dark oak button", Material.DARK_OAK_BUTTON),
        Map.entry("dark oak chest boat", Material.DARK_OAK_CHEST_BOAT),
        Map.entry("dark oak door", Material.DARK_OAK_DOOR),
        Map.entry("dark oak fence", Material.DARK_OAK_FENCE),
        Map.entry("dark oak fence gate", Material.DARK_OAK_FENCE_GATE),
        Map.entry("dark oak hanging sign", Material.DARK_OAK_HANGING_SIGN),
        Map.entry("dark oak leaves", Material.DARK_OAK_LEAVES),
        Map.entry("dark oak log", Material.DARK_OAK_LOG),
        Map.entry("dark oak planks", Material.DARK_OAK_PLANKS),
        Map.entry("dark oak pressure plate", Material.DARK_OAK_PRESSURE_PLATE),
        Map.entry("dark oak sapling", Material.DARK_OAK_SAPLING),
        Map.entry("dark oak sign", Material.DARK_OAK_SIGN),
        Map.entry("dark oak slab", Material.DARK_OAK_SLAB),
        Map.entry("dark oak stairs", Material.DARK_OAK_STAIRS),
        Map.entry("dark oak trapdoor", Material.DARK_OAK_TRAPDOOR),
        Map.entry("dark oak wall hanging sign", Material.DARK_OAK_WALL_HANGING_SIGN),
        Map.entry("dark oak wall sign", Material.DARK_OAK_WALL_SIGN),
        Map.entry("dark oak wood", Material.DARK_OAK_WOOD),
        Map.entry("dark prismarine", Material.DARK_PRISMARINE),
        Map.entry("dark prismarine slab", Material.DARK_PRISMARINE_SLAB),
        Map.entry("dark prismarine stairs", Material.DARK_PRISMARINE_STAIRS),
        Map.entry("daylight detector", Material.DAYLIGHT_DETECTOR),
        Map.entry("dead brain coral", Material.DEAD_BRAIN_CORAL),
        Map.entry("dead brain coral block", Material.DEAD_BRAIN_CORAL_BLOCK),
        Map.entry("dead brain coral fan", Material.DEAD_BRAIN_CORAL_FAN),
        Map.entry("dead brain coral wall fan", Material.DEAD_BRAIN_CORAL_WALL_FAN),
        Map.entry("dead bubble coral", Material.DEAD_BUBBLE_CORAL),
        Map.entry("dead bubble coral block", Material.DEAD_BUBBLE_CORAL_BLOCK),
        Map.entry("dead bubble coral fan", Material.DEAD_BUBBLE_CORAL_FAN),
        Map.entry("dead bubble coral wall fan", Material.DEAD_BUBBLE_CORAL_WALL_FAN),
        Map.entry("dead bush", Material.DEAD_BUSH),
        Map.entry("dead fire coral", Material.DEAD_FIRE_CORAL),
        Map.entry("dead fire coral block", Material.DEAD_FIRE_CORAL_BLOCK),
        Map.entry("dead fire coral fan", Material.DEAD_FIRE_CORAL_FAN),
        Map.entry("dead fire coral wall fan", Material.DEAD_FIRE_CORAL_WALL_FAN),
        Map.entry("dead horn coral", Material.DEAD_HORN_CORAL),
        Map.entry("dead horn coral block", Material.DEAD_HORN_CORAL_BLOCK),
        Map.entry("dead horn coral fan", Material.DEAD_HORN_CORAL_FAN),
        Map.entry("dead horn coral wall fan", Material.DEAD_HORN_CORAL_WALL_FAN),
        Map.entry("dead tube coral", Material.DEAD_TUBE_CORAL),
        Map.entry("dead tube coral block", Material.DEAD_TUBE_CORAL_BLOCK),
        Map.entry("dead tube coral fan", Material.DEAD_TUBE_CORAL_FAN),
        Map.entry("dead tube coral wall fan", Material.DEAD_TUBE_CORAL_WALL_FAN),
        Map.entry("debug stick", Material.DEBUG_STICK),
        Map.entry("decorated pot", Material.DECORATED_POT),
        Map.entry("deepslate", Material.DEEPSLATE),
        Map.entry("deepslate brick slab", Material.DEEPSLATE_BRICK_SLAB),
        Map.entry("deepslate brick stairs", Material.DEEPSLATE_BRICK_STAIRS),
        Map.entry("deepslate brick wall", Material.DEEPSLATE_BRICK_WALL),
        Map.entry("deepslate bricks", Material.DEEPSLATE_BRICKS),
        Map.entry("deepslate coal ore", Material.DEEPSLATE_COAL_ORE),
        Map.entry("deepslate copper ore", Material.DEEPSLATE_COPPER_ORE),
        Map.entry("deepslate diamond ore", Material.DEEPSLATE_DIAMOND_ORE),
        Map.entry("deepslate emerald ore", Material.DEEPSLATE_EMERALD_ORE),
        Map.entry("deepslate gold ore", Material.DEEPSLATE_GOLD_ORE),
        Map.entry("deepslate iron ore", Material.DEEPSLATE_IRON_ORE),
        Map.entry("deepslate lapis ore", Material.DEEPSLATE_LAPIS_ORE),
        Map.entry("deepslate redstone ore", Material.DEEPSLATE_REDSTONE_ORE),
        Map.entry("deepslate tile slab", Material.DEEPSLATE_TILE_SLAB),
        Map.entry("deepslate tile stairs", Material.DEEPSLATE_TILE_STAIRS),
        Map.entry("deepslate tile wall", Material.DEEPSLATE_TILE_WALL),
        Map.entry("deepslate tiles", Material.DEEPSLATE_TILES),
        Map.entry("detector rail", Material.DETECTOR_RAIL),
        Map.entry("diamond", Material.DIAMOND),
        Map.entry("diamond axe", Material.DIAMOND_AXE),
        Map.entry("diamond block", Material.DIAMOND_BLOCK),
        Map.entry("diamond boots", Material.DIAMOND_BOOTS),
        Map.entry("diamond chestplate", Material.DIAMOND_CHESTPLATE),
        Map.entry("diamond helmet", Material.DIAMOND_HELMET),
        Map.entry("diamond hoe", Material.DIAMOND_HOE),
        Map.entry("diamond horse armor", Material.DIAMOND_HORSE_ARMOR),
        Map.entry("diamond leggings", Material.DIAMOND_LEGGINGS),
        Map.entry("diamond ore", Material.DIAMOND_ORE),
        Map.entry("diamond pickaxe", Material.DIAMOND_PICKAXE),
        Map.entry("diamond shovel", Material.DIAMOND_SHOVEL),
        Map.entry("diamond sword", Material.DIAMOND_SWORD),
        Map.entry("diorite", Material.DIORITE),
        Map.entry("diorite slab", Material.DIORITE_SLAB),
        Map.entry("diorite stairs", Material.DIORITE_STAIRS),
        Map.entry("diorite wall", Material.DIORITE_WALL),
        Map.entry("dirt", Material.DIRT),
        Map.entry("dirt path", Material.DIRT_PATH),
        Map.entry("disc fragment 5", Material.DISC_FRAGMENT_5),
        Map.entry("dispenser", Material.DISPENSER),
        Map.entry("dolphin spawn egg", Material.DOLPHIN_SPAWN_EGG),
        Map.entry("donkey spawn egg", Material.DONKEY_SPAWN_EGG),
        Map.entry("dragon breath", Material.DRAGON_BREATH),
        Map.entry("dragon egg", Material.DRAGON_EGG),
        Map.entry("dragon head", Material.DRAGON_HEAD),
        Map.entry("dragon wall head", Material.DRAGON_WALL_HEAD),
        Map.entry("dried kelp", Material.DRIED_KELP),
        Map.entry("dried kelp block", Material.DRIED_KELP_BLOCK),
        Map.entry("dripstone block", Material.DRIPSTONE_BLOCK),
        Map.entry("dropper", Material.DROPPER),
        Map.entry("drowned spawn egg", Material.DROWNED_SPAWN_EGG),
        Map.entry("dune armor trim smithing template", Material.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE),
        Map.entry("echo shard", Material.ECHO_SHARD),
        Map.entry("egg", Material.EGG),
        Map.entry("elder guardian spawn egg", Material.ELDER_GUARDIAN_SPAWN_EGG),
        Map.entry("elytra", Material.ELYTRA),
        Map.entry("emerald", Material.EMERALD),
        Map.entry("emerald block", Material.EMERALD_BLOCK),
        Map.entry("emerald ore", Material.EMERALD_ORE),
        Map.entry("enchanted book", Material.ENCHANTED_BOOK),
        Map.entry("enchanted golden apple", Material.ENCHANTED_GOLDEN_APPLE),
        Map.entry("enchanting table", Material.ENCHANTING_TABLE),
        Map.entry("end crystal", Material.END_CRYSTAL),
        Map.entry("end gateway", Material.END_GATEWAY),
        Map.entry("end portal", Material.END_PORTAL),
        Map.entry("end portal frame", Material.END_PORTAL_FRAME),
        Map.entry("end rod", Material.END_ROD),
        Map.entry("end stone", Material.END_STONE),
        Map.entry("end stone brick slab", Material.END_STONE_BRICK_SLAB),
        Map.entry("end stone brick stairs", Material.END_STONE_BRICK_STAIRS),
        Map.entry("end stone brick wall", Material.END_STONE_BRICK_WALL),
        Map.entry("end stone bricks", Material.END_STONE_BRICKS),
        Map.entry("ender chest", Material.ENDER_CHEST),
        Map.entry("ender dragon spawn egg", Material.ENDER_DRAGON_SPAWN_EGG),
        Map.entry("ender eye", Material.ENDER_EYE),
        Map.entry("ender pearl", Material.ENDER_PEARL),
        Map.entry("enderman spawn egg", Material.ENDERMAN_SPAWN_EGG),
        Map.entry("endermite spawn egg", Material.ENDERMITE_SPAWN_EGG),
        Map.entry("evoker spawn egg", Material.EVOKER_SPAWN_EGG),
        Map.entry("experience bottle", Material.EXPERIENCE_BOTTLE),
        Map.entry("explorer pottery sherd", Material.EXPLORER_POTTERY_SHERD),
        Map.entry("exposed chiseled copper", Material.EXPOSED_CHISELED_COPPER),
        Map.entry("exposed copper", Material.EXPOSED_COPPER),
        Map.entry("exposed copper bulb", Material.EXPOSED_COPPER_BULB),
        Map.entry("exposed copper door", Material.EXPOSED_COPPER_DOOR),
        Map.entry("exposed copper grate", Material.EXPOSED_COPPER_GRATE),
        Map.entry("exposed copper trapdoor", Material.EXPOSED_COPPER_TRAPDOOR),
        Map.entry("exposed cut copper", Material.EXPOSED_CUT_COPPER),
        Map.entry("exposed cut copper slab", Material.EXPOSED_CUT_COPPER_SLAB),
        Map.entry("exposed cut copper stairs", Material.EXPOSED_CUT_COPPER_STAIRS),
        Map.entry("eye armor trim smithing template", Material.EYE_ARMOR_TRIM_SMITHING_TEMPLATE),
        Map.entry("farmland", Material.FARMLAND),
        Map.entry("feather", Material.FEATHER),
        Map.entry("fermented spider eye", Material.FERMENTED_SPIDER_EYE),
        Map.entry("fern", Material.FERN),
        Map.entry("field masoned banner pattern", Material.FIELD_MASONED_BANNER_PATTERN),
        Map.entry("filled map", Material.FILLED_MAP),
        Map.entry("fire", Material.FIRE),
        Map.entry("fire charge", Material.FIRE_CHARGE),
        Map.entry("fire coral", Material.FIRE_CORAL),
        Map.entry("fire coral block", Material.FIRE_CORAL_BLOCK),
        Map.entry("fire coral fan", Material.FIRE_CORAL_FAN),
        Map.entry("fire coral wall fan", Material.FIRE_CORAL_WALL_FAN),
        Map.entry("firefly bush", Material.FIREFLY_BUSH),
        Map.entry("firework rocket", Material.FIREWORK_ROCKET),
        Map.entry("firework star", Material.FIREWORK_STAR),
        Map.entry("fishing rod", Material.FISHING_ROD),
        Map.entry("fletching table", Material.FLETCHING_TABLE),
        Map.entry("flint", Material.FLINT),
        Map.entry("flint and steel", Material.FLINT_AND_STEEL),
        Map.entry("flow armor trim smithing template", Material.FLOW_ARMOR_TRIM_SMITHING_TEMPLATE),
        Map.entry("flow banner pattern", Material.FLOW_BANNER_PATTERN),
        Map.entry("flow pottery sherd", Material.FLOW_POTTERY_SHERD),
        Map.entry("flower banner pattern", Material.FLOWER_BANNER_PATTERN),
        Map.entry("flower pot", Material.FLOWER_POT),
        Map.entry("flowering azalea", Material.FLOWERING_AZALEA),
        Map.entry("flowering azalea leaves", Material.FLOWERING_AZALEA_LEAVES),
        Map.entry("fox spawn egg", Material.FOX_SPAWN_EGG),
        Map.entry("friend pottery sherd", Material.FRIEND_POTTERY_SHERD),
        Map.entry("frog spawn egg", Material.FROG_SPAWN_EGG),
        Map.entry("frogspawn", Material.FROGSPAWN),
        Map.entry("frosted ice", Material.FROSTED_ICE),
        Map.entry("furnace", Material.FURNACE),
        Map.entry("furnace minecart", Material.FURNACE_MINECART),
        Map.entry("ghast spawn egg", Material.GHAST_SPAWN_EGG),
        Map.entry("ghast tear", Material.GHAST_TEAR),
        Map.entry("gilded blackstone", Material.GILDED_BLACKSTONE),
        Map.entry("glass", Material.GLASS),
        Map.entry("glass bottle", Material.GLASS_BOTTLE),
        Map.entry("glass pane", Material.GLASS_PANE),
        Map.entry("glistering melon slice", Material.GLISTERING_MELON_SLICE),
        Map.entry("globe banner pattern", Material.GLOBE_BANNER_PATTERN),
        Map.entry("glow berries", Material.GLOW_BERRIES),
        Map.entry("glow ink sac", Material.GLOW_INK_SAC),
        Map.entry("glow item frame", Material.GLOW_ITEM_FRAME),
        Map.entry("glow lichen", Material.GLOW_LICHEN),
        Map.entry("glow squid spawn egg", Material.GLOW_SQUID_SPAWN_EGG),
        Map.entry("glowstone", Material.GLOWSTONE),
        Map.entry("glowstone dust", Material.GLOWSTONE_DUST),
        Map.entry("goat horn", Material.GOAT_HORN),
        Map.entry("goat spawn egg", Material.GOAT_SPAWN_EGG),
        Map.entry("gold block", Material.GOLD_BLOCK),
        Map.entry("gold ingot", Material.GOLD_INGOT),
        Map.entry("gold nugget", Material.GOLD_NUGGET),
        Map.entry("gold ore", Material.GOLD_ORE),
        Map.entry("golden apple", Material.GOLDEN_APPLE),
        Map.entry("golden axe", Material.GOLDEN_AXE),
        Map.entry("golden boots", Material.GOLDEN_BOOTS),
        Map.entry("golden carrot", Material.GOLDEN_CARROT),
        Map.entry("golden chestplate", Material.GOLDEN_CHESTPLATE),
        Map.entry("golden helmet", Material.GOLDEN_HELMET),
        Map.entry("golden hoe", Material.GOLDEN_HOE),
        Map.entry("golden horse armor", Material.GOLDEN_HORSE_ARMOR),
        Map.entry("golden leggings", Material.GOLDEN_LEGGINGS),
        Map.entry("golden pickaxe", Material.GOLDEN_PICKAXE),
        Map.entry("golden shovel", Material.GOLDEN_SHOVEL),
        Map.entry("golden sword", Material.GOLDEN_SWORD),
        Map.entry("granite", Material.GRANITE),
        Map.entry("granite slab", Material.GRANITE_SLAB),
        Map.entry("granite stairs", Material.GRANITE_STAIRS),
        Map.entry("granite wall", Material.GRANITE_WALL),
        Map.entry("grass block", Material.GRASS_BLOCK),
        Map.entry("gravel", Material.GRAVEL),
        Map.entry("gray banner", Material.GRAY_BANNER),
        Map.entry("gray bed", Material.GRAY_BED),
        Map.entry("gray bundle", Material.GRAY_BUNDLE),
        Map.entry("gray candle", Material.GRAY_CANDLE),
        Map.entry("gray candle cake", Material.GRAY_CANDLE_CAKE),
        Map.entry("gray carpet", Material.GRAY_CARPET),
        Map.entry("gray concrete", Material.GRAY_CONCRETE),
        Map.entry("gray concrete powder", Material.GRAY_CONCRETE_POWDER),
        Map.entry("gray dye", Material.GRAY_DYE),
        Map.entry("gray glazed terracotta", Material.GRAY_GLAZED_TERRACOTTA),
        Map.entry("gray shulker box", Material.GRAY_SHULKER_BOX),
        Map.entry("gray stained glass", Material.GRAY_STAINED_GLASS),
        Map.entry("gray stained glass pane", Material.GRAY_STAINED_GLASS_PANE),
        Map.entry("gray terracotta", Material.GRAY_TERRACOTTA),
        Map.entry("gray wall banner", Material.GRAY_WALL_BANNER),
        Map.entry("gray wool", Material.GRAY_WOOL),
        Map.entry("green banner", Material.GREEN_BANNER),
        Map.entry("green bed", Material.GREEN_BED),
        Map.entry("green bundle", Material.GREEN_BUNDLE),
        Map.entry("green candle", Material.GREEN_CANDLE),
        Map.entry("green candle cake", Material.GREEN_CANDLE_CAKE),
        Map.entry("green carpet", Material.GREEN_CARPET),
        Map.entry("green concrete", Material.GREEN_CONCRETE),
        Map.entry("green concrete powder", Material.GREEN_CONCRETE_POWDER),
        Map.entry("green dye", Material.GREEN_DYE),
        Map.entry("green glazed terracotta", Material.GREEN_GLAZED_TERRACOTTA),
        Map.entry("green shulker box", Material.GREEN_SHULKER_BOX),
        Map.entry("green stained glass", Material.GREEN_STAINED_GLASS),
        Map.entry("green stained glass pane", Material.GREEN_STAINED_GLASS_PANE),
        Map.entry("green terracotta", Material.GREEN_TERRACOTTA),
        Map.entry("green wall banner", Material.GREEN_WALL_BANNER),
        Map.entry("green wool", Material.GREEN_WOOL),
        Map.entry("grindstone", Material.GRINDSTONE),
        Map.entry("guardian spawn egg", Material.GUARDIAN_SPAWN_EGG),
        Map.entry("gunpowder", Material.GUNPOWDER),
        Map.entry("guster banner pattern", Material.GUSTER_BANNER_PATTERN),
        Map.entry("guster pottery sherd", Material.GUSTER_POTTERY_SHERD),
        Map.entry("hanging roots", Material.HANGING_ROOTS),
        Map.entry("hay block", Material.HAY_BLOCK),
        Map.entry("heart of the sea", Material.HEART_OF_THE_SEA),
        Map.entry("heart pottery sherd", Material.HEART_POTTERY_SHERD),
        Map.entry("heartbreak pottery sherd", Material.HEARTBREAK_POTTERY_SHERD),
        Map.entry("heavy core", Material.HEAVY_CORE),
        Map.entry("heavy weighted pressure plate", Material.HEAVY_WEIGHTED_PRESSURE_PLATE),
        Map.entry("hoglin spawn egg", Material.HOGLIN_SPAWN_EGG),
        Map.entry("honey block", Material.HONEY_BLOCK),
        Map.entry("honey bottle", Material.HONEY_BOTTLE),
        Map.entry("honeycomb", Material.HONEYCOMB),
        Map.entry("honeycomb block", Material.HONEYCOMB_BLOCK),
        Map.entry("hopper", Material.HOPPER),
        Map.entry("hopper minecart", Material.HOPPER_MINECART),
        Map.entry("horn coral", Material.HORN_CORAL),
        Map.entry("horn coral block", Material.HORN_CORAL_BLOCK),
        Map.entry("horn coral fan", Material.HORN_CORAL_FAN),
        Map.entry("horn coral wall fan", Material.HORN_CORAL_WALL_FAN),
        Map.entry("horse spawn egg", Material.HORSE_SPAWN_EGG),
        Map.entry("host armor trim smithing template", Material.HOST_ARMOR_TRIM_SMITHING_TEMPLATE),
        Map.entry("howl pottery sherd", Material.HOWL_POTTERY_SHERD),
        Map.entry("husk spawn egg", Material.HUSK_SPAWN_EGG),
        Map.entry("ice", Material.ICE),
        Map.entry("infested chiseled stone bricks", Material.INFESTED_CHISELED_STONE_BRICKS),
        Map.entry("infested cobblestone", Material.INFESTED_COBBLESTONE),
        Map.entry("infested cracked stone bricks", Material.INFESTED_CRACKED_STONE_BRICKS),
        Map.entry("infested deepslate", Material.INFESTED_DEEPSLATE),
        Map.entry("infested mossy stone bricks", Material.INFESTED_MOSSY_STONE_BRICKS),
        Map.entry("infested stone", Material.INFESTED_STONE),
        Map.entry("infested stone bricks", Material.INFESTED_STONE_BRICKS),
        Map.entry("ink sac", Material.INK_SAC),
        Map.entry("iron axe", Material.IRON_AXE),
        Map.entry("iron bars", Material.IRON_BARS),
        Map.entry("iron block", Material.IRON_BLOCK),
        Map.entry("iron boots", Material.IRON_BOOTS),
        Map.entry("iron chestplate", Material.IRON_CHESTPLATE),
        Map.entry("iron door", Material.IRON_DOOR),
        Map.entry("iron golem spawn egg", Material.IRON_GOLEM_SPAWN_EGG),
        Map.entry("iron helmet", Material.IRON_HELMET),
        Map.entry("iron hoe", Material.IRON_HOE),
        Map.entry("iron horse armor", Material.IRON_HORSE_ARMOR),
        Map.entry("iron ingot", Material.IRON_INGOT),
        Map.entry("iron leggings", Material.IRON_LEGGINGS),
        Map.entry("iron nugget", Material.IRON_NUGGET),
        Map.entry("iron ore", Material.IRON_ORE),
        Map.entry("iron pickaxe", Material.IRON_PICKAXE),
        Map.entry("iron shovel", Material.IRON_SHOVEL),
        Map.entry("iron sword", Material.IRON_SWORD),
        Map.entry("iron trapdoor", Material.IRON_TRAPDOOR),
        Map.entry("item frame", Material.ITEM_FRAME),
        Map.entry("jack o lantern", Material.JACK_O_LANTERN),
        Map.entry("jigsaw", Material.JIGSAW),
        Map.entry("jukebox", Material.JUKEBOX),
        Map.entry("jungle boat", Material.JUNGLE_BOAT),
        Map.entry("jungle button", Material.JUNGLE_BUTTON),
        Map.entry("jungle chest boat", Material.JUNGLE_CHEST_BOAT),
        Map.entry("jungle door", Material.JUNGLE_DOOR),
        Map.entry("jungle fence", Material.JUNGLE_FENCE),
        Map.entry("jungle fence gate", Material.JUNGLE_FENCE_GATE),
        Map.entry("jungle hanging sign", Material.JUNGLE_HANGING_SIGN),
        Map.entry("jungle leaves", Material.JUNGLE_LEAVES),
        Map.entry("jungle log", Material.JUNGLE_LOG),
        Map.entry("jungle planks", Material.JUNGLE_PLANKS),
        Map.entry("jungle pressure plate", Material.JUNGLE_PRESSURE_PLATE),
        Map.entry("jungle sapling", Material.JUNGLE_SAPLING),
        Map.entry("jungle sign", Material.JUNGLE_SIGN),
        Map.entry("jungle slab", Material.JUNGLE_SLAB),
        Map.entry("jungle stairs", Material.JUNGLE_STAIRS),
        Map.entry("jungle trapdoor", Material.JUNGLE_TRAPDOOR),
        Map.entry("jungle wall hanging sign", Material.JUNGLE_WALL_HANGING_SIGN),
        Map.entry("jungle wall sign", Material.JUNGLE_WALL_SIGN),
        Map.entry("jungle wood", Material.JUNGLE_WOOD),
        Map.entry("kelp", Material.KELP),
        Map.entry("kelp plant", Material.KELP_PLANT),
        Map.entry("knowledge book", Material.KNOWLEDGE_BOOK)
    );

    public static String applyMaterialPlaceholders(String input) {
        for (Map.Entry<String, Material> entry : MATERIAL_ALIASES.entrySet()) {
            input = input.replace(entry.getKey(), entry.getValue().name());
        }
        return input;
    }
}
